// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: payroll_record.
// - Entity ID: 102019b37c0727473a2a0b6fee4a8682372.
// - Entity Version: 102019b46b63649785993ecd62a04b5d5cc.
// - Task ID: 694964e9424ce9326ca7b3ba.
// - Task Root ID: 6945719feb5090bdee671a86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for PayrollRecordStatus
 */
export enum PayrollRecordStatus {
  Unspecified = 0,
  Draft = 1,
  Approved = 2,
  Paid = 3,
}



/**
 * Interface for PayrollRecordModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface PayrollRecordModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  worker_id: string;
  company_id: string;
  pay_period_start: string;
  pay_period_end: string;
  hourly_wage: number;
  hours_worked: number;
  total_pay: number;
  status: PayrollRecordStatus;
}

/**
 * ORM class for PayrollRecord entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class PayrollRecordORM {
  private static instance: PayrollRecordORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b37c0727473a2a0b6fee4a8682372';
    this.entityName = 'payroll_record';
    this.entityVersion = '102019b46b63649785993ecd62a04b5d5cc';
    this.taskId = '694964e9424ce9326ca7b3ba';
    this.taskRootId = '6945719feb5090bdee671a86';
  }

  /**
   * Get singleton instance of PayrollRecordORM
   */
  public static getInstance(): PayrollRecordORM {
    if (!PayrollRecordORM.instance) {
      PayrollRecordORM.instance = new PayrollRecordORM();
    }

    return PayrollRecordORM.instance;
  }

  /**
   * Get payroll_record by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getPayrollRecordByIDs(ids: string[]): Promise<PayrollRecordModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete payroll_record by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deletePayrollRecordByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all PayrollRecord records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllPayrollRecord(): Promise<PayrollRecordModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new PayrollRecord record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertPayrollRecord(data: PayrollRecordModel[]): Promise<PayrollRecordModel[]> {
    const structured = data.map((item) => CreateData(PayrollRecordModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all PayrollRecord records
   */
  async purgeAllPayrollRecord(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List PayrollRecord records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listPayrollRecord(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[PayrollRecordModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get payroll_record by Id index
   * This function gets data by index.
   */
  async getPayrollRecordById(
    id: string,
  ): Promise<PayrollRecordModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) payroll_record by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPayrollRecordById(
    id: string,
    data: PayrollRecordModel
  ): Promise<PayrollRecordModel[]> {
    const index = createIndexId(
      id
    );

    const values = PayrollRecordModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete payroll_record by Id index
   */
  async deletePayrollRecordById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get payroll_record by CompanyIdWorkerId index
   * This function gets data by index.
   */
  async getPayrollRecordByCompanyIdWorkerId(
    company_id: string,
    worker_id: string,
  ): Promise<PayrollRecordModel[]> {
    const index = createIndexCompanyIdWorkerId(
      company_id,
      worker_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) payroll_record by CompanyIdWorkerId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPayrollRecordByCompanyIdWorkerId(
    company_id: string,
    worker_id: string,
    data: PayrollRecordModel
  ): Promise<PayrollRecordModel[]> {
    const index = createIndexCompanyIdWorkerId(
      company_id,
      worker_id
    );

    const values = PayrollRecordModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete payroll_record by CompanyIdWorkerId index
   */
  async deletePayrollRecordByCompanyIdWorkerId(
    company_id: string,
    worker_id: string
  ): Promise<void> {
    const index = createIndexCompanyIdWorkerId(
      company_id,
      worker_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get payroll_record by CompanyIdPayPeriodStart index
   * This function gets data by index.
   */
  async getPayrollRecordByCompanyIdPayPeriodStart(
    company_id: string,
    pay_period_start: string,
  ): Promise<PayrollRecordModel[]> {
    const index = createIndexCompanyIdPayPeriodStart(
      company_id,
      pay_period_start
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) payroll_record by CompanyIdPayPeriodStart index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPayrollRecordByCompanyIdPayPeriodStart(
    company_id: string,
    pay_period_start: string,
    data: PayrollRecordModel
  ): Promise<PayrollRecordModel[]> {
    const index = createIndexCompanyIdPayPeriodStart(
      company_id,
      pay_period_start
    );

    const values = PayrollRecordModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete payroll_record by CompanyIdPayPeriodStart index
   */
  async deletePayrollRecordByCompanyIdPayPeriodStart(
    company_id: string,
    pay_period_start: string
  ): Promise<void> {
    const index = createIndexCompanyIdPayPeriodStart(
      company_id,
      pay_period_start
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get payroll_record by DataCreator index
   * This function gets data by index.
   */
  async getPayrollRecordByDataCreator(
    data_creator: string,
  ): Promise<PayrollRecordModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) payroll_record by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPayrollRecordByDataCreator(
    data_creator: string,
    data: PayrollRecordModel
  ): Promise<PayrollRecordModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = PayrollRecordModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete payroll_record by DataCreator index
   */
  async deletePayrollRecordByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get payroll_record by DataUpdater index
   * This function gets data by index.
   */
  async getPayrollRecordByDataUpdater(
    data_updater: string,
  ): Promise<PayrollRecordModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) payroll_record by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPayrollRecordByDataUpdater(
    data_updater: string,
    data: PayrollRecordModel
  ): Promise<PayrollRecordModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = PayrollRecordModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete payroll_record by DataUpdater index
   */
  async deletePayrollRecordByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to PayrollRecordModel data array
   */
  private resultToData(values: Data[]): PayrollRecordModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return PayrollRecordModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as PayrollRecordModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized PayrollRecordModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is PayrollRecordModel => item !== null);
  }
}

/**
 * Convert PayrollRecordModel data to Value array
 */
function PayrollRecordModelToValues(data: PayrollRecordModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'worker_id', type: DataType.string, defaultValue: '' },
    { key: 'company_id', type: DataType.string, defaultValue: '' },
    { key: 'pay_period_start', type: DataType.string, defaultValue: '' },
    { key: 'pay_period_end', type: DataType.string, defaultValue: '' },
    { key: 'hourly_wage', type: DataType.number, defaultValue: 0 },
    { key: 'hours_worked', type: DataType.number, defaultValue: 0 },
    { key: 'total_pay', type: DataType.number, defaultValue: 0 },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof PayrollRecordModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to PayrollRecordModel data
 */
function PayrollRecordModelFromValues(values: Value[]): PayrollRecordModel {
  const data: Partial<PayrollRecordModel> = {};

  for (const value of values) {
    if (!value.name) continue;

    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'worker_id':
        data.worker_id = ParseValue(value, DataType.string) as string;
        break;
      case 'company_id':
        data.company_id = ParseValue(value, DataType.string) as string;
        break;
      case 'pay_period_start':
        data.pay_period_start = ParseValue(value, DataType.string) as string;
        break;
      case 'pay_period_end':
        data.pay_period_end = ParseValue(value, DataType.string) as string;
        break;
      case 'hourly_wage':
        data.hourly_wage = ParseValue(value, DataType.number) as number;
        break;
      case 'hours_worked':
        data.hours_worked = ParseValue(value, DataType.number) as number;
        break;
      case 'total_pay':
        data.total_pay = ParseValue(value, DataType.number) as number;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as PayrollRecordStatus;
        break;
    }
  }

  return data as PayrollRecordModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for CompanyIdWorkerId fields
 */
function createIndexCompanyIdWorkerId(
  company_id: string,
  worker_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, company_id, 'company_id'),
    CreateValue(DataType.string, worker_id, 'worker_id'),
  ];

  return {
    fields: ['company_id', 'worker_id'],
    values
  };
}
/**
 * Create index for CompanyIdPayPeriodStart fields
 */
function createIndexCompanyIdPayPeriodStart(
  company_id: string,
  pay_period_start: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, company_id, 'company_id'),
    CreateValue(DataType.string, pay_period_start, 'pay_period_start'),
  ];

  return {
    fields: ['company_id', 'pay_period_start'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default PayrollRecordORM;