// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: vehicle_schedule.
// - Entity ID: 102019b374d03bc7cfb8cb1485a8fef65a0.
// - Entity Version: 102019b46b63649785993ecd62a04b5d5cc.
// - Task ID: 694964e9424ce9326ca7b3ba.
// - Task Root ID: 6945719feb5090bdee671a86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for VehicleScheduleMaintenanceType
 */
export enum VehicleScheduleMaintenanceType {
  Unspecified = 0,
  Preventive = 1,
  Repair = 2,
  Inspection = 3,
}
/**
 * Enumeration for VehicleScheduleStatus
 */
export enum VehicleScheduleStatus {
  Unspecified = 0,
  Available = 1,
  InUse = 2,
  Maintenance = 3,
}



/**
 * Interface for VehicleScheduleModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface VehicleScheduleModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  vehicle_id: string;
  company_id: string;
  schedule_date: string;
  status: VehicleScheduleStatus;
  maintenance_type?: VehicleScheduleMaintenanceType | null;
}

/**
 * ORM class for VehicleSchedule entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class VehicleScheduleORM {
  private static instance: VehicleScheduleORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b374d03bc7cfb8cb1485a8fef65a0';
    this.entityName = 'vehicle_schedule';
    this.entityVersion = '102019b46b63649785993ecd62a04b5d5cc';
    this.taskId = '694964e9424ce9326ca7b3ba';
    this.taskRootId = '6945719feb5090bdee671a86';
  }

  /**
   * Get singleton instance of VehicleScheduleORM
   */
  public static getInstance(): VehicleScheduleORM {
    if (!VehicleScheduleORM.instance) {
      VehicleScheduleORM.instance = new VehicleScheduleORM();
    }

    return VehicleScheduleORM.instance;
  }

  /**
   * Get vehicle_schedule by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getVehicleScheduleByIDs(ids: string[]): Promise<VehicleScheduleModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete vehicle_schedule by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteVehicleScheduleByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all VehicleSchedule records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllVehicleSchedule(): Promise<VehicleScheduleModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new VehicleSchedule record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertVehicleSchedule(data: VehicleScheduleModel[]): Promise<VehicleScheduleModel[]> {
    const structured = data.map((item) => CreateData(VehicleScheduleModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all VehicleSchedule records
   */
  async purgeAllVehicleSchedule(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List VehicleSchedule records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listVehicleSchedule(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[VehicleScheduleModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get vehicle_schedule by Id index
   * This function gets data by index.
   */
  async getVehicleScheduleById(
    id: string,
  ): Promise<VehicleScheduleModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) vehicle_schedule by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVehicleScheduleById(
    id: string,
    data: VehicleScheduleModel
  ): Promise<VehicleScheduleModel[]> {
    const index = createIndexId(
      id
    );

    const values = VehicleScheduleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete vehicle_schedule by Id index
   */
  async deleteVehicleScheduleById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get vehicle_schedule by ScheduleDateVehicleId index
   * This function gets data by index.
   */
  async getVehicleScheduleByScheduleDateVehicleId(
    schedule_date: string,
    vehicle_id: string,
  ): Promise<VehicleScheduleModel[]> {
    const index = createIndexScheduleDateVehicleId(
      schedule_date,
      vehicle_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) vehicle_schedule by ScheduleDateVehicleId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVehicleScheduleByScheduleDateVehicleId(
    schedule_date: string,
    vehicle_id: string,
    data: VehicleScheduleModel
  ): Promise<VehicleScheduleModel[]> {
    const index = createIndexScheduleDateVehicleId(
      schedule_date,
      vehicle_id
    );

    const values = VehicleScheduleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete vehicle_schedule by ScheduleDateVehicleId index
   */
  async deleteVehicleScheduleByScheduleDateVehicleId(
    schedule_date: string,
    vehicle_id: string
  ): Promise<void> {
    const index = createIndexScheduleDateVehicleId(
      schedule_date,
      vehicle_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get vehicle_schedule by CompanyIdScheduleDate index
   * This function gets data by index.
   */
  async getVehicleScheduleByCompanyIdScheduleDate(
    company_id: string,
    schedule_date: string,
  ): Promise<VehicleScheduleModel[]> {
    const index = createIndexCompanyIdScheduleDate(
      company_id,
      schedule_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) vehicle_schedule by CompanyIdScheduleDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVehicleScheduleByCompanyIdScheduleDate(
    company_id: string,
    schedule_date: string,
    data: VehicleScheduleModel
  ): Promise<VehicleScheduleModel[]> {
    const index = createIndexCompanyIdScheduleDate(
      company_id,
      schedule_date
    );

    const values = VehicleScheduleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete vehicle_schedule by CompanyIdScheduleDate index
   */
  async deleteVehicleScheduleByCompanyIdScheduleDate(
    company_id: string,
    schedule_date: string
  ): Promise<void> {
    const index = createIndexCompanyIdScheduleDate(
      company_id,
      schedule_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get vehicle_schedule by DataCreator index
   * This function gets data by index.
   */
  async getVehicleScheduleByDataCreator(
    data_creator: string,
  ): Promise<VehicleScheduleModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) vehicle_schedule by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVehicleScheduleByDataCreator(
    data_creator: string,
    data: VehicleScheduleModel
  ): Promise<VehicleScheduleModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = VehicleScheduleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete vehicle_schedule by DataCreator index
   */
  async deleteVehicleScheduleByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get vehicle_schedule by DataUpdater index
   * This function gets data by index.
   */
  async getVehicleScheduleByDataUpdater(
    data_updater: string,
  ): Promise<VehicleScheduleModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) vehicle_schedule by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setVehicleScheduleByDataUpdater(
    data_updater: string,
    data: VehicleScheduleModel
  ): Promise<VehicleScheduleModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = VehicleScheduleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete vehicle_schedule by DataUpdater index
   */
  async deleteVehicleScheduleByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to VehicleScheduleModel data array
   */
  private resultToData(values: Data[]): VehicleScheduleModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return VehicleScheduleModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as VehicleScheduleModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized VehicleScheduleModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is VehicleScheduleModel => item !== null);
  }
}

/**
 * Convert VehicleScheduleModel data to Value array
 */
function VehicleScheduleModelToValues(data: VehicleScheduleModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'vehicle_id', type: DataType.string, defaultValue: '' },
    { key: 'company_id', type: DataType.string, defaultValue: '' },
    { key: 'schedule_date', type: DataType.string, defaultValue: '' },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'maintenance_type', type: DataType.enumeration, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof VehicleScheduleModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to VehicleScheduleModel data
 */
function VehicleScheduleModelFromValues(values: Value[]): VehicleScheduleModel {
  const data: Partial<VehicleScheduleModel> = {};

  for (const value of values) {
    if (!value.name) continue;

    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'vehicle_id':
        data.vehicle_id = ParseValue(value, DataType.string) as string;
        break;
      case 'company_id':
        data.company_id = ParseValue(value, DataType.string) as string;
        break;
      case 'schedule_date':
        data.schedule_date = ParseValue(value, DataType.string) as string;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as VehicleScheduleStatus;
        break;
      case 'maintenance_type':
        data.maintenance_type = ParseValue(value, DataType.enumeration) as VehicleScheduleMaintenanceType | null;
        break;
    }
  }

  return data as VehicleScheduleModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for ScheduleDateVehicleId fields
 */
function createIndexScheduleDateVehicleId(
  schedule_date: string,
  vehicle_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, schedule_date, 'schedule_date'),
    CreateValue(DataType.string, vehicle_id, 'vehicle_id'),
  ];

  return {
    fields: ['schedule_date', 'vehicle_id'],
    values
  };
}
/**
 * Create index for CompanyIdScheduleDate fields
 */
function createIndexCompanyIdScheduleDate(
  company_id: string,
  schedule_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, company_id, 'company_id'),
    CreateValue(DataType.string, schedule_date, 'schedule_date'),
  ];

  return {
    fields: ['company_id', 'schedule_date'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default VehicleScheduleORM;