// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: worker.
// - Entity ID: 102019b374acae47bf5ba6c06b2ef6295e9.
// - Entity Version: 102019b46b63649785993ecd62a04b5d5cc.
// - Task ID: 694964e9424ce9326ca7b3ba.
// - Task Root ID: 6945719feb5090bdee671a86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for WorkerRole
 */
export enum WorkerRole {
  Unspecified = 0,
  Mover = 1,
  Driver = 2,
  Supervisor = 3,
}
/**
 * Enumeration for WorkerStatus
 */
export enum WorkerStatus {
  Unspecified = 0,
  Active = 1,
  Inactive = 2,
}



/**
 * Interface for WorkerModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface WorkerModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  full_name: string;
  role: WorkerRole;
  status: WorkerStatus;
  company_id: string;
}

/**
 * ORM class for Worker entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class WorkerORM {
  private static instance: WorkerORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b374acae47bf5ba6c06b2ef6295e9';
    this.entityName = 'worker';
    this.entityVersion = '102019b46b63649785993ecd62a04b5d5cc';
    this.taskId = '694964e9424ce9326ca7b3ba';
    this.taskRootId = '6945719feb5090bdee671a86';
  }

  /**
   * Get singleton instance of WorkerORM
   */
  public static getInstance(): WorkerORM {
    if (!WorkerORM.instance) {
      WorkerORM.instance = new WorkerORM();
    }

    return WorkerORM.instance;
  }

  /**
   * Get worker by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getWorkerByIDs(ids: string[]): Promise<WorkerModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete worker by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteWorkerByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Worker records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllWorker(): Promise<WorkerModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Worker record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertWorker(data: WorkerModel[]): Promise<WorkerModel[]> {
    const structured = data.map((item) => CreateData(WorkerModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Worker records
   */
  async purgeAllWorker(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Worker records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listWorker(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[WorkerModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get worker by Id index
   * This function gets data by index.
   */
  async getWorkerById(
    id: string,
  ): Promise<WorkerModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) worker by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkerById(
    id: string,
    data: WorkerModel
  ): Promise<WorkerModel[]> {
    const index = createIndexId(
      id
    );

    const values = WorkerModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete worker by Id index
   */
  async deleteWorkerById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get worker by CompanyIdStatus index
   * This function gets data by index.
   */
  async getWorkerByCompanyIdStatus(
    company_id: string,
    status: WorkerStatus,
  ): Promise<WorkerModel[]> {
    const index = createIndexCompanyIdStatus(
      company_id,
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) worker by CompanyIdStatus index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkerByCompanyIdStatus(
    company_id: string,
    status: WorkerStatus,
    data: WorkerModel
  ): Promise<WorkerModel[]> {
    const index = createIndexCompanyIdStatus(
      company_id,
      status
    );

    const values = WorkerModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete worker by CompanyIdStatus index
   */
  async deleteWorkerByCompanyIdStatus(
    company_id: string,
    status: WorkerStatus
  ): Promise<void> {
    const index = createIndexCompanyIdStatus(
      company_id,
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get worker by CompanyIdRole index
   * This function gets data by index.
   */
  async getWorkerByCompanyIdRole(
    company_id: string,
    role: WorkerRole,
  ): Promise<WorkerModel[]> {
    const index = createIndexCompanyIdRole(
      company_id,
      role
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) worker by CompanyIdRole index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkerByCompanyIdRole(
    company_id: string,
    role: WorkerRole,
    data: WorkerModel
  ): Promise<WorkerModel[]> {
    const index = createIndexCompanyIdRole(
      company_id,
      role
    );

    const values = WorkerModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete worker by CompanyIdRole index
   */
  async deleteWorkerByCompanyIdRole(
    company_id: string,
    role: WorkerRole
  ): Promise<void> {
    const index = createIndexCompanyIdRole(
      company_id,
      role
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get worker by DataCreator index
   * This function gets data by index.
   */
  async getWorkerByDataCreator(
    data_creator: string,
  ): Promise<WorkerModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) worker by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkerByDataCreator(
    data_creator: string,
    data: WorkerModel
  ): Promise<WorkerModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = WorkerModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete worker by DataCreator index
   */
  async deleteWorkerByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get worker by DataUpdater index
   * This function gets data by index.
   */
  async getWorkerByDataUpdater(
    data_updater: string,
  ): Promise<WorkerModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) worker by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setWorkerByDataUpdater(
    data_updater: string,
    data: WorkerModel
  ): Promise<WorkerModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = WorkerModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete worker by DataUpdater index
   */
  async deleteWorkerByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to WorkerModel data array
   */
  private resultToData(values: Data[]): WorkerModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return WorkerModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as WorkerModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized WorkerModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is WorkerModel => item !== null);
  }
}

/**
 * Convert WorkerModel data to Value array
 */
function WorkerModelToValues(data: WorkerModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'full_name', type: DataType.string, defaultValue: '' },
    { key: 'role', type: DataType.enumeration, defaultValue: 0 },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'company_id', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof WorkerModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to WorkerModel data
 */
function WorkerModelFromValues(values: Value[]): WorkerModel {
  const data: Partial<WorkerModel> = {};

  for (const value of values) {
    if (!value.name) continue;

    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'full_name':
        data.full_name = ParseValue(value, DataType.string) as string;
        break;
      case 'role':
        data.role = ParseValue(value, DataType.enumeration) as WorkerRole;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as WorkerStatus;
        break;
      case 'company_id':
        data.company_id = ParseValue(value, DataType.string) as string;
        break;
    }
  }

  return data as WorkerModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for CompanyIdStatus fields
 */
function createIndexCompanyIdStatus(
  company_id: string,
  status: WorkerStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, company_id, 'company_id'),
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['company_id', 'status'],
    values
  };
}
/**
 * Create index for CompanyIdRole fields
 */
function createIndexCompanyIdRole(
  company_id: string,
  role: WorkerRole
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, company_id, 'company_id'),
    CreateValue(DataType.enumeration, role, 'role'),
  ];

  return {
    fields: ['company_id', 'role'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default WorkerORM;