// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: job.
// - Entity ID: 102019b374acae47f20aae623df0810c686.
// - Entity Version: 102019b46b63649785993ecd62a04b5d5cc.
// - Task ID: 694964e9424ce9326ca7b3ba.
// - Task Root ID: 6945719feb5090bdee671a86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for JobStatus
 */
export enum JobStatus {
  Unspecified = 0,
  Quote = 1,
  Booked = 2,
  InProgress = 3,
  Completed = 4,
  Canceled = 5,
}



/**
 * Interface for JobModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface JobModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  company_id: string;
  customer_name: string;
  status: JobStatus;
  scheduled_date: string;
  pickup_address: string;
  dropoff_address: string;
  estimated_cost?: number | null;
  inventory_data?: string;
}

/**
 * ORM class for Job entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class JobORM {
  private static instance: JobORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b374acae47f20aae623df0810c686';
    this.entityName = 'job';
    this.entityVersion = '102019b46b63649785993ecd62a04b5d5cc';
    this.taskId = '694964e9424ce9326ca7b3ba';
    this.taskRootId = '6945719feb5090bdee671a86';
  }

  /**
   * Get singleton instance of JobORM
   */
  public static getInstance(): JobORM {
    if (!JobORM.instance) {
      JobORM.instance = new JobORM();
    }

    return JobORM.instance;
  }

  /**
   * Get job by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getJobByIDs(ids: string[]): Promise<JobModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteJobByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Job records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllJob(): Promise<JobModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Job record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertJob(data: JobModel[]): Promise<JobModel[]> {
    const structured = data.map((item) => {
      const values = JobModelToValues(item);
      // Filter out fields that should be auto-generated by backend
      const autoGeneratedFields = ['id', 'data_creator', 'data_updater', 'create_time', 'update_time'];
      const filteredValues = values.filter(v => !autoGeneratedFields.includes(v.name || ''));
      return CreateData(filteredValues);
    });

    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Job records
   */
  async purgeAllJob(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Job records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listJob(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[JobModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get job by Id index
   * This function gets data by index.
   */
  async getJobById(
    id: string,
  ): Promise<JobModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobById(
    id: string,
    data: JobModel
  ): Promise<JobModel[]> {
    const index = createIndexId(
      id
    );

    const values = JobModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job by Id index
   */
  async deleteJobById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job by CompanyIdStatus index
   * This function gets data by index.
   */
  async getJobByCompanyIdStatus(
    company_id: string,
    status: JobStatus,
  ): Promise<JobModel[]> {
    const index = createIndexCompanyIdStatus(
      company_id,
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job by CompanyIdStatus index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobByCompanyIdStatus(
    company_id: string,
    status: JobStatus,
    data: JobModel
  ): Promise<JobModel[]> {
    const index = createIndexCompanyIdStatus(
      company_id,
      status
    );

    const values = JobModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job by CompanyIdStatus index
   */
  async deleteJobByCompanyIdStatus(
    company_id: string,
    status: JobStatus
  ): Promise<void> {
    const index = createIndexCompanyIdStatus(
      company_id,
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job by CompanyIdScheduledDate index
   * This function gets data by index.
   */
  async getJobByCompanyIdScheduledDate(
    company_id: string,
    scheduled_date: string,
  ): Promise<JobModel[]> {
    const index = createIndexCompanyIdScheduledDate(
      company_id,
      scheduled_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job by CompanyIdScheduledDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobByCompanyIdScheduledDate(
    company_id: string,
    scheduled_date: string,
    data: JobModel
  ): Promise<JobModel[]> {
    const index = createIndexCompanyIdScheduledDate(
      company_id,
      scheduled_date
    );

    const values = JobModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job by CompanyIdScheduledDate index
   */
  async deleteJobByCompanyIdScheduledDate(
    company_id: string,
    scheduled_date: string
  ): Promise<void> {
    const index = createIndexCompanyIdScheduledDate(
      company_id,
      scheduled_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job by DataCreator index
   * This function gets data by index.
   */
  async getJobByDataCreator(
    data_creator: string,
  ): Promise<JobModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobByDataCreator(
    data_creator: string,
    data: JobModel
  ): Promise<JobModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = JobModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job by DataCreator index
   */
  async deleteJobByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job by DataUpdater index
   * This function gets data by index.
   */
  async getJobByDataUpdater(
    data_updater: string,
  ): Promise<JobModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobByDataUpdater(
    data_updater: string,
    data: JobModel
  ): Promise<JobModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = JobModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job by DataUpdater index
   */
  async deleteJobByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to JobModel data array
   */
  private resultToData(values: Data[]): JobModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return JobModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as JobModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized JobModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is JobModel => item !== null);
  }
}

/**
 * Convert JobModel data to Value array
 */
function JobModelToValues(data: JobModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'company_id', type: DataType.string, defaultValue: '' },
    { key: 'customer_name', type: DataType.string, defaultValue: '' },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'scheduled_date', type: DataType.string, defaultValue: '' },
    { key: 'pickup_address', type: DataType.string, defaultValue: '' },
    { key: 'dropoff_address', type: DataType.string, defaultValue: '' },
    { key: 'estimated_cost', type: DataType.number, defaultValue: null },
    { key: 'inventory_data', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof JobModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to JobModel data
 */
function JobModelFromValues(values: Value[]): JobModel {
  const data: Partial<JobModel> = {};

  for (const value of values) {
    if (!value.name) continue;

    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'company_id':
        data.company_id = ParseValue(value, DataType.string) as string;
        break;
      case 'customer_name':
        data.customer_name = ParseValue(value, DataType.string) as string;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as JobStatus;
        break;
      case 'scheduled_date':
        data.scheduled_date = ParseValue(value, DataType.string) as string;
        break;
      case 'pickup_address':
        data.pickup_address = ParseValue(value, DataType.string) as string;
        break;
      case 'dropoff_address':
        data.dropoff_address = ParseValue(value, DataType.string) as string;
        break;
      case 'estimated_cost':
        data.estimated_cost = ParseValue(value, DataType.number) as number | null;
        break;
      case 'inventory_data':
        data.inventory_data = ParseValue(value, DataType.string) as string;
        break;
    }
  }

  return data as JobModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for CompanyIdStatus fields
 */
function createIndexCompanyIdStatus(
  company_id: string,
  status: JobStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, company_id, 'company_id'),
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['company_id', 'status'],
    values
  };
}
/**
 * Create index for CompanyIdScheduledDate fields
 */
function createIndexCompanyIdScheduledDate(
  company_id: string,
  scheduled_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, company_id, 'company_id'),
    CreateValue(DataType.string, scheduled_date, 'scheduled_date'),
  ];

  return {
    fields: ['company_id', 'scheduled_date'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default JobORM;