// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: equipment_schedule.
// - Entity ID: 102019b374d03bc7afc81fc57a81704ab7a.
// - Entity Version: 102019b46b63649785993ecd62a04b5d5cc.
// - Task ID: 694964e9424ce9326ca7b3ba.
// - Task Root ID: 6945719feb5090bdee671a86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for EquipmentScheduleStatus
 */
export enum EquipmentScheduleStatus {
  Unspecified = 0,
  Available = 1,
  Reserved = 2,
  InMaintenance = 3,
}



/**
 * Interface for EquipmentScheduleModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface EquipmentScheduleModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  equipment_id: string;
  company_id: string;
  schedule_date: string;
  status: EquipmentScheduleStatus;
  reason?: string | null;
}

/**
 * ORM class for EquipmentSchedule entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class EquipmentScheduleORM {
  private static instance: EquipmentScheduleORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b374d03bc7afc81fc57a81704ab7a';
    this.entityName = 'equipment_schedule';
    this.entityVersion = '102019b46b63649785993ecd62a04b5d5cc';
    this.taskId = '694964e9424ce9326ca7b3ba';
    this.taskRootId = '6945719feb5090bdee671a86';
  }

  /**
   * Get singleton instance of EquipmentScheduleORM
   */
  public static getInstance(): EquipmentScheduleORM {
    if (!EquipmentScheduleORM.instance) {
      EquipmentScheduleORM.instance = new EquipmentScheduleORM();
    }

    return EquipmentScheduleORM.instance;
  }

  /**
   * Get equipment_schedule by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getEquipmentScheduleByIDs(ids: string[]): Promise<EquipmentScheduleModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete equipment_schedule by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteEquipmentScheduleByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all EquipmentSchedule records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllEquipmentSchedule(): Promise<EquipmentScheduleModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new EquipmentSchedule record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertEquipmentSchedule(data: EquipmentScheduleModel[]): Promise<EquipmentScheduleModel[]> {
    const structured = data.map((item) => CreateData(EquipmentScheduleModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all EquipmentSchedule records
   */
  async purgeAllEquipmentSchedule(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List EquipmentSchedule records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listEquipmentSchedule(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[EquipmentScheduleModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get equipment_schedule by Id index
   * This function gets data by index.
   */
  async getEquipmentScheduleById(
    id: string,
  ): Promise<EquipmentScheduleModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) equipment_schedule by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setEquipmentScheduleById(
    id: string,
    data: EquipmentScheduleModel
  ): Promise<EquipmentScheduleModel[]> {
    const index = createIndexId(
      id
    );

    const values = EquipmentScheduleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete equipment_schedule by Id index
   */
  async deleteEquipmentScheduleById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get equipment_schedule by EquipmentIdScheduleDate index
   * This function gets data by index.
   */
  async getEquipmentScheduleByEquipmentIdScheduleDate(
    equipment_id: string,
    schedule_date: string,
  ): Promise<EquipmentScheduleModel[]> {
    const index = createIndexEquipmentIdScheduleDate(
      equipment_id,
      schedule_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) equipment_schedule by EquipmentIdScheduleDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setEquipmentScheduleByEquipmentIdScheduleDate(
    equipment_id: string,
    schedule_date: string,
    data: EquipmentScheduleModel
  ): Promise<EquipmentScheduleModel[]> {
    const index = createIndexEquipmentIdScheduleDate(
      equipment_id,
      schedule_date
    );

    const values = EquipmentScheduleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete equipment_schedule by EquipmentIdScheduleDate index
   */
  async deleteEquipmentScheduleByEquipmentIdScheduleDate(
    equipment_id: string,
    schedule_date: string
  ): Promise<void> {
    const index = createIndexEquipmentIdScheduleDate(
      equipment_id,
      schedule_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get equipment_schedule by CompanyIdScheduleDate index
   * This function gets data by index.
   */
  async getEquipmentScheduleByCompanyIdScheduleDate(
    company_id: string,
    schedule_date: string,
  ): Promise<EquipmentScheduleModel[]> {
    const index = createIndexCompanyIdScheduleDate(
      company_id,
      schedule_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) equipment_schedule by CompanyIdScheduleDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setEquipmentScheduleByCompanyIdScheduleDate(
    company_id: string,
    schedule_date: string,
    data: EquipmentScheduleModel
  ): Promise<EquipmentScheduleModel[]> {
    const index = createIndexCompanyIdScheduleDate(
      company_id,
      schedule_date
    );

    const values = EquipmentScheduleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete equipment_schedule by CompanyIdScheduleDate index
   */
  async deleteEquipmentScheduleByCompanyIdScheduleDate(
    company_id: string,
    schedule_date: string
  ): Promise<void> {
    const index = createIndexCompanyIdScheduleDate(
      company_id,
      schedule_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get equipment_schedule by DataCreator index
   * This function gets data by index.
   */
  async getEquipmentScheduleByDataCreator(
    data_creator: string,
  ): Promise<EquipmentScheduleModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) equipment_schedule by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setEquipmentScheduleByDataCreator(
    data_creator: string,
    data: EquipmentScheduleModel
  ): Promise<EquipmentScheduleModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = EquipmentScheduleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete equipment_schedule by DataCreator index
   */
  async deleteEquipmentScheduleByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get equipment_schedule by DataUpdater index
   * This function gets data by index.
   */
  async getEquipmentScheduleByDataUpdater(
    data_updater: string,
  ): Promise<EquipmentScheduleModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) equipment_schedule by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setEquipmentScheduleByDataUpdater(
    data_updater: string,
    data: EquipmentScheduleModel
  ): Promise<EquipmentScheduleModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = EquipmentScheduleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete equipment_schedule by DataUpdater index
   */
  async deleteEquipmentScheduleByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to EquipmentScheduleModel data array
   */
  private resultToData(values: Data[]): EquipmentScheduleModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return EquipmentScheduleModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as EquipmentScheduleModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized EquipmentScheduleModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is EquipmentScheduleModel => item !== null);
  }
}

/**
 * Convert EquipmentScheduleModel data to Value array
 */
function EquipmentScheduleModelToValues(data: EquipmentScheduleModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'equipment_id', type: DataType.string, defaultValue: '' },
    { key: 'company_id', type: DataType.string, defaultValue: '' },
    { key: 'schedule_date', type: DataType.string, defaultValue: '' },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'reason', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof EquipmentScheduleModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to EquipmentScheduleModel data
 */
function EquipmentScheduleModelFromValues(values: Value[]): EquipmentScheduleModel {
  const data: Partial<EquipmentScheduleModel> = {};

  for (const value of values) {
    if (!value.name) continue;

    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'equipment_id':
        data.equipment_id = ParseValue(value, DataType.string) as string;
        break;
      case 'company_id':
        data.company_id = ParseValue(value, DataType.string) as string;
        break;
      case 'schedule_date':
        data.schedule_date = ParseValue(value, DataType.string) as string;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as EquipmentScheduleStatus;
        break;
      case 'reason':
        data.reason = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }

  return data as EquipmentScheduleModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for EquipmentIdScheduleDate fields
 */
function createIndexEquipmentIdScheduleDate(
  equipment_id: string,
  schedule_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, equipment_id, 'equipment_id'),
    CreateValue(DataType.string, schedule_date, 'schedule_date'),
  ];

  return {
    fields: ['equipment_id', 'schedule_date'],
    values
  };
}
/**
 * Create index for CompanyIdScheduleDate fields
 */
function createIndexCompanyIdScheduleDate(
  company_id: string,
  schedule_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, company_id, 'company_id'),
    CreateValue(DataType.string, schedule_date, 'schedule_date'),
  ];

  return {
    fields: ['company_id', 'schedule_date'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default EquipmentScheduleORM;