// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: job_equipment_allocation.
// - Entity ID: 102019b374acae47a03823bb9420cb34504.
// - Entity Version: 102019b46b63649785993ecd62a04b5d5cc.
// - Task ID: 694964e9424ce9326ca7b3ba.
// - Task Root ID: 6945719feb5090bdee671a86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for JobEquipmentAllocationModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface JobEquipmentAllocationModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  company_id: string;
  job_id: string;
  equipment_id: string;
  quantity_assigned: number;
}

/**
 * ORM class for JobEquipmentAllocation entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class JobEquipmentAllocationORM {
  private static instance: JobEquipmentAllocationORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b374acae47a03823bb9420cb34504';
    this.entityName = 'job_equipment_allocation';
    this.entityVersion = '102019b46b63649785993ecd62a04b5d5cc';
    this.taskId = '694964e9424ce9326ca7b3ba';
    this.taskRootId = '6945719feb5090bdee671a86';
  }

  /**
   * Get singleton instance of JobEquipmentAllocationORM
   */
  public static getInstance(): JobEquipmentAllocationORM {
    if (!JobEquipmentAllocationORM.instance) {
      JobEquipmentAllocationORM.instance = new JobEquipmentAllocationORM();
    }

    return JobEquipmentAllocationORM.instance;
  }

  /**
   * Get job_equipment_allocation by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getJobEquipmentAllocationByIDs(ids: string[]): Promise<JobEquipmentAllocationModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_equipment_allocation by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteJobEquipmentAllocationByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all JobEquipmentAllocation records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllJobEquipmentAllocation(): Promise<JobEquipmentAllocationModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new JobEquipmentAllocation record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertJobEquipmentAllocation(data: JobEquipmentAllocationModel[]): Promise<JobEquipmentAllocationModel[]> {
    const structured = data.map((item) => CreateData(JobEquipmentAllocationModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all JobEquipmentAllocation records
   */
  async purgeAllJobEquipmentAllocation(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List JobEquipmentAllocation records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listJobEquipmentAllocation(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[JobEquipmentAllocationModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get job_equipment_allocation by Id index
   * This function gets data by index.
   */
  async getJobEquipmentAllocationById(
    id: string,
  ): Promise<JobEquipmentAllocationModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_equipment_allocation by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobEquipmentAllocationById(
    id: string,
    data: JobEquipmentAllocationModel
  ): Promise<JobEquipmentAllocationModel[]> {
    const index = createIndexId(
      id
    );

    const values = JobEquipmentAllocationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_equipment_allocation by Id index
   */
  async deleteJobEquipmentAllocationById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job_equipment_allocation by JobId index
   * This function gets data by index.
   */
  async getJobEquipmentAllocationByJobId(
    job_id: string,
  ): Promise<JobEquipmentAllocationModel[]> {
    const index = createIndexJobId(
      job_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_equipment_allocation by JobId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobEquipmentAllocationByJobId(
    job_id: string,
    data: JobEquipmentAllocationModel
  ): Promise<JobEquipmentAllocationModel[]> {
    const index = createIndexJobId(
      job_id
    );

    const values = JobEquipmentAllocationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_equipment_allocation by JobId index
   */
  async deleteJobEquipmentAllocationByJobId(
    job_id: string
  ): Promise<void> {
    const index = createIndexJobId(
      job_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job_equipment_allocation by EquipmentId index
   * This function gets data by index.
   */
  async getJobEquipmentAllocationByEquipmentId(
    equipment_id: string,
  ): Promise<JobEquipmentAllocationModel[]> {
    const index = createIndexEquipmentId(
      equipment_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_equipment_allocation by EquipmentId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobEquipmentAllocationByEquipmentId(
    equipment_id: string,
    data: JobEquipmentAllocationModel
  ): Promise<JobEquipmentAllocationModel[]> {
    const index = createIndexEquipmentId(
      equipment_id
    );

    const values = JobEquipmentAllocationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_equipment_allocation by EquipmentId index
   */
  async deleteJobEquipmentAllocationByEquipmentId(
    equipment_id: string
  ): Promise<void> {
    const index = createIndexEquipmentId(
      equipment_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job_equipment_allocation by DataCreator index
   * This function gets data by index.
   */
  async getJobEquipmentAllocationByDataCreator(
    data_creator: string,
  ): Promise<JobEquipmentAllocationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_equipment_allocation by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobEquipmentAllocationByDataCreator(
    data_creator: string,
    data: JobEquipmentAllocationModel
  ): Promise<JobEquipmentAllocationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = JobEquipmentAllocationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_equipment_allocation by DataCreator index
   */
  async deleteJobEquipmentAllocationByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job_equipment_allocation by DataUpdater index
   * This function gets data by index.
   */
  async getJobEquipmentAllocationByDataUpdater(
    data_updater: string,
  ): Promise<JobEquipmentAllocationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_equipment_allocation by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobEquipmentAllocationByDataUpdater(
    data_updater: string,
    data: JobEquipmentAllocationModel
  ): Promise<JobEquipmentAllocationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = JobEquipmentAllocationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_equipment_allocation by DataUpdater index
   */
  async deleteJobEquipmentAllocationByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to JobEquipmentAllocationModel data array
   */
  private resultToData(values: Data[]): JobEquipmentAllocationModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return JobEquipmentAllocationModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as JobEquipmentAllocationModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized JobEquipmentAllocationModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is JobEquipmentAllocationModel => item !== null);
  }
}

/**
 * Convert JobEquipmentAllocationModel data to Value array
 */
function JobEquipmentAllocationModelToValues(data: JobEquipmentAllocationModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'company_id', type: DataType.string, defaultValue: '' },
    { key: 'job_id', type: DataType.string, defaultValue: '' },
    { key: 'equipment_id', type: DataType.string, defaultValue: '' },
    { key: 'quantity_assigned', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof JobEquipmentAllocationModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to JobEquipmentAllocationModel data
 */
function JobEquipmentAllocationModelFromValues(values: Value[]): JobEquipmentAllocationModel {
  const data: Partial<JobEquipmentAllocationModel> = {};

  for (const value of values) {
    if (!value.name) continue;

    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'company_id':
        data.company_id = ParseValue(value, DataType.string) as string;
        break;
      case 'job_id':
        data.job_id = ParseValue(value, DataType.string) as string;
        break;
      case 'equipment_id':
        data.equipment_id = ParseValue(value, DataType.string) as string;
        break;
      case 'quantity_assigned':
        data.quantity_assigned = ParseValue(value, DataType.number) as number;
        break;
    }
  }

  return data as JobEquipmentAllocationModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for JobId fields
 */
function createIndexJobId(
  job_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, job_id, 'job_id'),
  ];

  return {
    fields: ['job_id'],
    values
  };
}
/**
 * Create index for EquipmentId fields
 */
function createIndexEquipmentId(
  equipment_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, equipment_id, 'equipment_id'),
  ];

  return {
    fields: ['equipment_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default JobEquipmentAllocationORM;