// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: company.
// - Entity ID: 102019b374acae47b2a9249747d1ec0013a.
// - Entity Version: 102019b46b63649785993ecd62a04b5d5cc.
// - Task ID: 694964e9424ce9326ca7b3ba.
// - Task Root ID: 6945719feb5090bdee671a86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for CompanyModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface CompanyModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  name: string;
  license_number?: string | null;
  contact_email: string;
}

/**
 * ORM class for Company entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class CompanyORM {
  private static instance: CompanyORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b374acae47b2a9249747d1ec0013a';
    this.entityName = 'company';
    this.entityVersion = '102019b46b63649785993ecd62a04b5d5cc';
    this.taskId = '694964e9424ce9326ca7b3ba';
    this.taskRootId = '6945719feb5090bdee671a86';
  }

  /**
   * Get singleton instance of CompanyORM
   */
  public static getInstance(): CompanyORM {
    if (!CompanyORM.instance) {
      CompanyORM.instance = new CompanyORM();
    }

    return CompanyORM.instance;
  }

  /**
   * Get company by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getCompanyByIDs(ids: string[]): Promise<CompanyModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete company by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteCompanyByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Company records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllCompany(): Promise<CompanyModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Company record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertCompany(data: CompanyModel[]): Promise<CompanyModel[]> {
    const structured = data.map((item) => CreateData(CompanyModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Company records
   */
  async purgeAllCompany(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Company records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listCompany(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[CompanyModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get company by Id index
   * This function gets data by index.
   */
  async getCompanyById(
    id: string,
  ): Promise<CompanyModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) company by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCompanyById(
    id: string,
    data: CompanyModel
  ): Promise<CompanyModel[]> {
    const index = createIndexId(
      id
    );

    const values = CompanyModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete company by Id index
   */
  async deleteCompanyById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get company by Name index
   * This function gets data by index.
   */
  async getCompanyByName(
    name: string,
  ): Promise<CompanyModel[]> {
    const index = createIndexName(
      name
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) company by Name index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCompanyByName(
    name: string,
    data: CompanyModel
  ): Promise<CompanyModel[]> {
    const index = createIndexName(
      name
    );

    const values = CompanyModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete company by Name index
   */
  async deleteCompanyByName(
    name: string
  ): Promise<void> {
    const index = createIndexName(
      name
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get company by DataCreator index
   * This function gets data by index.
   */
  async getCompanyByDataCreator(
    data_creator: string,
  ): Promise<CompanyModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) company by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCompanyByDataCreator(
    data_creator: string,
    data: CompanyModel
  ): Promise<CompanyModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = CompanyModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete company by DataCreator index
   */
  async deleteCompanyByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get company by DataUpdater index
   * This function gets data by index.
   */
  async getCompanyByDataUpdater(
    data_updater: string,
  ): Promise<CompanyModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) company by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCompanyByDataUpdater(
    data_updater: string,
    data: CompanyModel
  ): Promise<CompanyModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = CompanyModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete company by DataUpdater index
   */
  async deleteCompanyByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to CompanyModel data array
   */
  private resultToData(values: Data[]): CompanyModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return CompanyModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as CompanyModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized CompanyModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is CompanyModel => item !== null);
  }
}

/**
 * Convert CompanyModel data to Value array
 */
function CompanyModelToValues(data: CompanyModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'name', type: DataType.string, defaultValue: '' },
    { key: 'license_number', type: DataType.string, defaultValue: null },
    { key: 'contact_email', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof CompanyModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to CompanyModel data
 */
function CompanyModelFromValues(values: Value[]): CompanyModel {
  const data: Partial<CompanyModel> = {};

  for (const value of values) {
    if (!value.name) continue;

    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'name':
        data.name = ParseValue(value, DataType.string) as string;
        break;
      case 'license_number':
        data.license_number = ParseValue(value, DataType.string) as string | null;
        break;
      case 'contact_email':
        data.contact_email = ParseValue(value, DataType.string) as string;
        break;
    }
  }

  return data as CompanyModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for Name fields
 */
function createIndexName(
  name: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, name, 'name'),
  ];

  return {
    fields: ['name'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default CompanyORM;