// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: job_worker_assignment.
// - Entity ID: 102019b374acae476e990a482bc9a79ad07.
// - Entity Version: 102019b46b63649785993ecd62a04b5d5cc.
// - Task ID: 694964e9424ce9326ca7b3ba.
// - Task Root ID: 6945719feb5090bdee671a86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for JobWorkerAssignmentModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface JobWorkerAssignmentModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  company_id: string;
  job_id: string;
  worker_id: string;
}

/**
 * ORM class for JobWorkerAssignment entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class JobWorkerAssignmentORM {
  private static instance: JobWorkerAssignmentORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b374acae476e990a482bc9a79ad07';
    this.entityName = 'job_worker_assignment';
    this.entityVersion = '102019b46b63649785993ecd62a04b5d5cc';
    this.taskId = '694964e9424ce9326ca7b3ba';
    this.taskRootId = '6945719feb5090bdee671a86';
  }

  /**
   * Get singleton instance of JobWorkerAssignmentORM
   */
  public static getInstance(): JobWorkerAssignmentORM {
    if (!JobWorkerAssignmentORM.instance) {
      JobWorkerAssignmentORM.instance = new JobWorkerAssignmentORM();
    }

    return JobWorkerAssignmentORM.instance;
  }

  /**
   * Get job_worker_assignment by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getJobWorkerAssignmentByIDs(ids: string[]): Promise<JobWorkerAssignmentModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_worker_assignment by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteJobWorkerAssignmentByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all JobWorkerAssignment records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllJobWorkerAssignment(): Promise<JobWorkerAssignmentModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new JobWorkerAssignment record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertJobWorkerAssignment(data: JobWorkerAssignmentModel[]): Promise<JobWorkerAssignmentModel[]> {
    const structured = data.map((item) => CreateData(JobWorkerAssignmentModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all JobWorkerAssignment records
   */
  async purgeAllJobWorkerAssignment(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List JobWorkerAssignment records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listJobWorkerAssignment(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[JobWorkerAssignmentModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get job_worker_assignment by Id index
   * This function gets data by index.
   */
  async getJobWorkerAssignmentById(
    id: string,
  ): Promise<JobWorkerAssignmentModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_worker_assignment by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobWorkerAssignmentById(
    id: string,
    data: JobWorkerAssignmentModel
  ): Promise<JobWorkerAssignmentModel[]> {
    const index = createIndexId(
      id
    );

    const values = JobWorkerAssignmentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_worker_assignment by Id index
   */
  async deleteJobWorkerAssignmentById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job_worker_assignment by JobId index
   * This function gets data by index.
   */
  async getJobWorkerAssignmentByJobId(
    job_id: string,
  ): Promise<JobWorkerAssignmentModel[]> {
    const index = createIndexJobId(
      job_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_worker_assignment by JobId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobWorkerAssignmentByJobId(
    job_id: string,
    data: JobWorkerAssignmentModel
  ): Promise<JobWorkerAssignmentModel[]> {
    const index = createIndexJobId(
      job_id
    );

    const values = JobWorkerAssignmentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_worker_assignment by JobId index
   */
  async deleteJobWorkerAssignmentByJobId(
    job_id: string
  ): Promise<void> {
    const index = createIndexJobId(
      job_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job_worker_assignment by WorkerId index
   * This function gets data by index.
   */
  async getJobWorkerAssignmentByWorkerId(
    worker_id: string,
  ): Promise<JobWorkerAssignmentModel[]> {
    const index = createIndexWorkerId(
      worker_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_worker_assignment by WorkerId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobWorkerAssignmentByWorkerId(
    worker_id: string,
    data: JobWorkerAssignmentModel
  ): Promise<JobWorkerAssignmentModel[]> {
    const index = createIndexWorkerId(
      worker_id
    );

    const values = JobWorkerAssignmentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_worker_assignment by WorkerId index
   */
  async deleteJobWorkerAssignmentByWorkerId(
    worker_id: string
  ): Promise<void> {
    const index = createIndexWorkerId(
      worker_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job_worker_assignment by DataCreator index
   * This function gets data by index.
   */
  async getJobWorkerAssignmentByDataCreator(
    data_creator: string,
  ): Promise<JobWorkerAssignmentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_worker_assignment by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobWorkerAssignmentByDataCreator(
    data_creator: string,
    data: JobWorkerAssignmentModel
  ): Promise<JobWorkerAssignmentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = JobWorkerAssignmentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_worker_assignment by DataCreator index
   */
  async deleteJobWorkerAssignmentByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job_worker_assignment by DataUpdater index
   * This function gets data by index.
   */
  async getJobWorkerAssignmentByDataUpdater(
    data_updater: string,
  ): Promise<JobWorkerAssignmentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_worker_assignment by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobWorkerAssignmentByDataUpdater(
    data_updater: string,
    data: JobWorkerAssignmentModel
  ): Promise<JobWorkerAssignmentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = JobWorkerAssignmentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_worker_assignment by DataUpdater index
   */
  async deleteJobWorkerAssignmentByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to JobWorkerAssignmentModel data array
   */
  private resultToData(values: Data[]): JobWorkerAssignmentModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return JobWorkerAssignmentModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as JobWorkerAssignmentModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized JobWorkerAssignmentModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is JobWorkerAssignmentModel => item !== null);
  }
}

/**
 * Convert JobWorkerAssignmentModel data to Value array
 */
function JobWorkerAssignmentModelToValues(data: JobWorkerAssignmentModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'company_id', type: DataType.string, defaultValue: '' },
    { key: 'job_id', type: DataType.string, defaultValue: '' },
    { key: 'worker_id', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof JobWorkerAssignmentModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to JobWorkerAssignmentModel data
 */
function JobWorkerAssignmentModelFromValues(values: Value[]): JobWorkerAssignmentModel {
  const data: Partial<JobWorkerAssignmentModel> = {};

  for (const value of values) {
    if (!value.name) continue;

    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'company_id':
        data.company_id = ParseValue(value, DataType.string) as string;
        break;
      case 'job_id':
        data.job_id = ParseValue(value, DataType.string) as string;
        break;
      case 'worker_id':
        data.worker_id = ParseValue(value, DataType.string) as string;
        break;
    }
  }

  return data as JobWorkerAssignmentModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for JobId fields
 */
function createIndexJobId(
  job_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, job_id, 'job_id'),
  ];

  return {
    fields: ['job_id'],
    values
  };
}
/**
 * Create index for WorkerId fields
 */
function createIndexWorkerId(
  worker_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, worker_id, 'worker_id'),
  ];

  return {
    fields: ['worker_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default JobWorkerAssignmentORM;