// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: job_vehicle_assignment.
// - Entity ID: 102019b374acae478dd93908c9423e638cc.
// - Entity Version: 102019b46b63649785993ecd62a04b5d5cc.
// - Task ID: 694964e9424ce9326ca7b3ba.
// - Task Root ID: 6945719feb5090bdee671a86.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for JobVehicleAssignmentModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface JobVehicleAssignmentModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  company_id: string;
  job_id: string;
  vehicle_id: string;
}

/**
 * ORM class for JobVehicleAssignment entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class JobVehicleAssignmentORM {
  private static instance: JobVehicleAssignmentORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b374acae478dd93908c9423e638cc';
    this.entityName = 'job_vehicle_assignment';
    this.entityVersion = '102019b46b63649785993ecd62a04b5d5cc';
    this.taskId = '694964e9424ce9326ca7b3ba';
    this.taskRootId = '6945719feb5090bdee671a86';
  }

  /**
   * Get singleton instance of JobVehicleAssignmentORM
   */
  public static getInstance(): JobVehicleAssignmentORM {
    if (!JobVehicleAssignmentORM.instance) {
      JobVehicleAssignmentORM.instance = new JobVehicleAssignmentORM();
    }

    return JobVehicleAssignmentORM.instance;
  }

  /**
   * Get job_vehicle_assignment by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getJobVehicleAssignmentByIDs(ids: string[]): Promise<JobVehicleAssignmentModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_vehicle_assignment by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteJobVehicleAssignmentByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all JobVehicleAssignment records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllJobVehicleAssignment(): Promise<JobVehicleAssignmentModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new JobVehicleAssignment record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertJobVehicleAssignment(data: JobVehicleAssignmentModel[]): Promise<JobVehicleAssignmentModel[]> {
    const structured = data.map((item) => CreateData(JobVehicleAssignmentModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all JobVehicleAssignment records
   */
  async purgeAllJobVehicleAssignment(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List JobVehicleAssignment records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listJobVehicleAssignment(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[JobVehicleAssignmentModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get job_vehicle_assignment by Id index
   * This function gets data by index.
   */
  async getJobVehicleAssignmentById(
    id: string,
  ): Promise<JobVehicleAssignmentModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_vehicle_assignment by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobVehicleAssignmentById(
    id: string,
    data: JobVehicleAssignmentModel
  ): Promise<JobVehicleAssignmentModel[]> {
    const index = createIndexId(
      id
    );

    const values = JobVehicleAssignmentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_vehicle_assignment by Id index
   */
  async deleteJobVehicleAssignmentById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job_vehicle_assignment by JobId index
   * This function gets data by index.
   */
  async getJobVehicleAssignmentByJobId(
    job_id: string,
  ): Promise<JobVehicleAssignmentModel[]> {
    const index = createIndexJobId(
      job_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_vehicle_assignment by JobId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobVehicleAssignmentByJobId(
    job_id: string,
    data: JobVehicleAssignmentModel
  ): Promise<JobVehicleAssignmentModel[]> {
    const index = createIndexJobId(
      job_id
    );

    const values = JobVehicleAssignmentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_vehicle_assignment by JobId index
   */
  async deleteJobVehicleAssignmentByJobId(
    job_id: string
  ): Promise<void> {
    const index = createIndexJobId(
      job_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job_vehicle_assignment by VehicleId index
   * This function gets data by index.
   */
  async getJobVehicleAssignmentByVehicleId(
    vehicle_id: string,
  ): Promise<JobVehicleAssignmentModel[]> {
    const index = createIndexVehicleId(
      vehicle_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_vehicle_assignment by VehicleId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobVehicleAssignmentByVehicleId(
    vehicle_id: string,
    data: JobVehicleAssignmentModel
  ): Promise<JobVehicleAssignmentModel[]> {
    const index = createIndexVehicleId(
      vehicle_id
    );

    const values = JobVehicleAssignmentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_vehicle_assignment by VehicleId index
   */
  async deleteJobVehicleAssignmentByVehicleId(
    vehicle_id: string
  ): Promise<void> {
    const index = createIndexVehicleId(
      vehicle_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job_vehicle_assignment by DataCreator index
   * This function gets data by index.
   */
  async getJobVehicleAssignmentByDataCreator(
    data_creator: string,
  ): Promise<JobVehicleAssignmentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_vehicle_assignment by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobVehicleAssignmentByDataCreator(
    data_creator: string,
    data: JobVehicleAssignmentModel
  ): Promise<JobVehicleAssignmentModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = JobVehicleAssignmentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_vehicle_assignment by DataCreator index
   */
  async deleteJobVehicleAssignmentByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get job_vehicle_assignment by DataUpdater index
   * This function gets data by index.
   */
  async getJobVehicleAssignmentByDataUpdater(
    data_updater: string,
  ): Promise<JobVehicleAssignmentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) job_vehicle_assignment by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setJobVehicleAssignmentByDataUpdater(
    data_updater: string,
    data: JobVehicleAssignmentModel
  ): Promise<JobVehicleAssignmentModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = JobVehicleAssignmentModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete job_vehicle_assignment by DataUpdater index
   */
  async deleteJobVehicleAssignmentByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to JobVehicleAssignmentModel data array
   */
  private resultToData(values: Data[]): JobVehicleAssignmentModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return JobVehicleAssignmentModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as JobVehicleAssignmentModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized JobVehicleAssignmentModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is JobVehicleAssignmentModel => item !== null);
  }
}

/**
 * Convert JobVehicleAssignmentModel data to Value array
 */
function JobVehicleAssignmentModelToValues(data: JobVehicleAssignmentModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'company_id', type: DataType.string, defaultValue: '' },
    { key: 'job_id', type: DataType.string, defaultValue: '' },
    { key: 'vehicle_id', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof JobVehicleAssignmentModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to JobVehicleAssignmentModel data
 */
function JobVehicleAssignmentModelFromValues(values: Value[]): JobVehicleAssignmentModel {
  const data: Partial<JobVehicleAssignmentModel> = {};

  for (const value of values) {
    if (!value.name) continue;

    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'company_id':
        data.company_id = ParseValue(value, DataType.string) as string;
        break;
      case 'job_id':
        data.job_id = ParseValue(value, DataType.string) as string;
        break;
      case 'vehicle_id':
        data.vehicle_id = ParseValue(value, DataType.string) as string;
        break;
    }
  }

  return data as JobVehicleAssignmentModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for JobId fields
 */
function createIndexJobId(
  job_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, job_id, 'job_id'),
  ];

  return {
    fields: ['job_id'],
    values
  };
}
/**
 * Create index for VehicleId fields
 */
function createIndexVehicleId(
  vehicle_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, vehicle_id, 'vehicle_id'),
  ];

  return {
    fields: ['vehicle_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default JobVehicleAssignmentORM;